### PR TITLE
Add green theme 

### PR DESCRIPTION
**Pull request by redian23**
# Before
Screenshot from 2019-09-13 21-57-00
Screenshot from 2019-09-13 21-57-10
# After
Screenshot from 2019-09-13 22-58-09Screenshot from 2019-09-13 22-58-25

### CODE REVIEW

**Comment by alainm23** [comment]
Wao the green color looks amazing.

**Comment by redian23** [comment]
> Wao the green color looks amazing.
Thx)

**Comment by alainm23** [comment]
What do you think?

image

**Comment by redian23** [comment]
I like it)

**Pull request merged**
