### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon was too flat and so, it doesn't look so good. It also didn't comply by the [eOS HIG](https://elementary.io/docs/human-interface-guidelines#shadows) regarding shadows and highlights, implementation of pictograms, outline.  Pictogram should be inset or extruded.

### CODE REVIEW

**Comment by alainm23** [comment]
I like the new design but I would prefer the music icon to be white.

**Comment by Fatih20** [comment]
Done. Added the bytes (get it?) at the bottom to represent sound. Kinda like the logo of [Melody](https://appcenter.elementary.io/com.github.artemanufrij.playmymusic/)

**Comment by Fatih20** [comment]
You want the bars removed? Just want to confirms because your sentence is a bit confusing.

We MUST be some ways to differentiate this app's icon from others music player already existing. We need to be better than a note slapped onto a base shape. Any suggestion besides the bar?

**Comment by Fatih20** [comment]
That was why I attempted to make the icon inset, like a chunk of the base shape shaped like a note is bitten off. Because most icons already uses extruded effect (look at the eOS HIG regarding pictograms). I want the icons to be unique. Any suggestions?

**Comment by alainm23** [comment]
In that sense I would also like the icon to be different.
How about adding dark bars like the 'Give Me Lyrics' icon
image

**Comment by Fatih20** [comment]
But, dark bars on the give me lyrics icon is a metaphor of a lyric sheet. This apps doesn't provide lyrics, it doesn't work.

The bar that I added is a metaphor for a common UI interface used in most apps that interacted with sound. This UI interface is used to monitor the volume of a sound.

Here's an example in Audacity : 
Screenshot-20190807231459-804x303

**Comment by Fatih20** [comment]
Alternatively, like I said, we could change courses 180 degree and experiment with headphones and sound wave.

**Comment by alainm23** [comment]
In the not too distant future Byte will support lyrics.

image

**Comment by alainm23** [comment]
I would like to see your experiment.

**Comment by Fatih20** [comment]
That's pretty damn cool, however, still, Byte primary purpose is to play music, not provide lyrics. You can make a  table on LibreOffice Writer but its primary purpose is not to make table, it's to process words. Making table is just a supplemental feature. And so, Libreoffice Writer is marketed as a word processor, as such, it's logo features metaphor of a document with words in them.

**Comment by alainm23** [comment]
You are right. I'm just a programmer 😅️

**Comment by Fatih20** [comment]
I don't think the first experimental design would work because it's just too cramped. I do think that the second one has potential because it is pretty unique compared to other music player.

**Comment by jtrees** [comment]
Chiming in, in case anyone is interested.

- I much prefer the original colour of the icon. It is more vibrant, and more unique. In any case the icon colour should match the GUI accent colour.
- As mentioned by others, the bars are distracting and introduce too much noise (same for experiment 2).
- The shape of the note in the original icon (thinner, vertical lines are closer) is more appealing.
- The note should be extruded and have a shadow, like on the Elementary Music app icon.
- The icon is pretty generic and looks a LOT like the iTunes icon. I don't actually mind this, but consider this line from the guidelines:
> Avoid simply slapping an element onto a base shape; use a unique outline to make your icon more distinct.
- The experimental icons attempt to address the latter issue. Experimental icon one definitely has potential (though admittedly, I am not fully convinced yet). Perhaps some more experiments would be a good idea.
- The icon doesn't appear to be related to the app name in any way. I'm not sure what the idea behind the name is, but adding some kind of "digital" element to the icon might be cool. Maybe a sort of pixelation/dissolving effect (sort of like [this](https://www.dreamstime.com/fractured-gear-dotted-vector-icon-disintegration-effect-square-items-organized-dissolving-shape-pixel-shows-speed-image118052659))? Of course, this is probably hard to get right without introducing too much noise and detail.

Anyway, kudos for starting this discussion. I look forward to the final icon.

**Comment by Fatih20** [comment]
But that's what those "bars" meant. Those aren't even bars by the way, they are boxes that is aligned with each other. It's supposed to be a metaphor for equalizer. Of which are supposed to be the digital element you're talking about. That's also supposed to represent the byte part of this apps name.

**Comment by Fatih20** [comment]
https://www.vecteezy.com/vector-art/106859-abstract-free-vector-music-equalizer
Thar's what I'm using as a metaphor for this icon because frankly, there's not much metaphor that there is without avoiding looking like an ituneslogo (of which I heavily dislike)

**Comment by jtrees** [comment]
> But that's what those "bars" meant. Those aren't even bars by the way, they are boxes that is aligned with each other. It's supposed to be a metaphor for equalizer. Of which are supposed to be the digital element you're talking about. That's also supposed to represent the byte part of this apps name.

I see. Well the equalizer and the notes seem to be competing with each other. Perhaps only the equalizer would be sufficient? Then it wouldn't even need to be in a circle and could have a more distinct icon shape. One would just have to ensure that it's still recognizable as a music player icon.

**Comment by Fatih20** [comment]
Problem is, equalizer is tend to be kept to the ground due to its nature in the real world. That's why I put the musical note before as inset instead of extruded, because it gives more contrast between the bright equalizer part and the musical note part. 

Leaving just the equalizer would leave the above part of the icon hollow and would be more fitting for a DAW instead of a simple music player.

**Comment by Fatih20** [comment]
What do you think? @alainm23

**Comment by alainm23** [comment]
Wao, this looks amazing, great job.

**Comment by alainm23** [comment]
@Fatih20 I could resolve the conflict to be able to do the merge.

**Comment by Fatih20** [comment]
Epic!

**Pull request merged**
