### PR TITLE
Add minimize button on HeaderBar

### PR DESCRIPTION
**Pull request by redian23**
I think minimize button need when need to save app in dashboard (plank)  without close.
Close button remove app with plank.

Screenshot from 2019-09-19 15-16-14

### CODE REVIEW

**Comment by alainm23** [comment]
I'm not sure if this is the best way to do it. And according to the elementary style guide, the minimize button is unnecessary. If the player is working in the background and is not shown in Plank, you can make Byte appear using the sound indicator.

**Comment by redian23** [comment]
Good.
It's just offer to do.
/--/--/
I find bug, in wingpanel don't switch play/stop button.
today trued fix him in MediaKey.vala, but i could not.
 
Screenshot from 2019-09-19 16-28-03
Screenshot from 2019-09-19 16-28-09

**Comment by alainm23** [comment]
Yes, I also see the error. I will try to fix it. I'm sorry, I don't use Telegram.

**Comment by redian23** [comment]
t's a pity! 
Will close Pull_rec
if anything i will write you on Gmail.

**Pull request closed without merging**
